apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: database
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
        - image: sani1994/grpc-vs-rest-database:latest
          name: grpc-vs-rest-database
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
