apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -o ./k8s/
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-server
  name: flask-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -o ./k8s/
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-server
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: userdb
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: sani1994/grpc-vs-rest-flask:latest
          name: grpc-vs-rest-flask
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          resources: {}
      restartPolicy: Always
status: {}
